version: '3.4'
services:
  prometheus:
    image: 'prom/prometheus:latest'
    container_name: prometheus_${ENV}
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
  grafana:
    image: 'grafana/grafana-oss'
    container_name: grafana_${ENV}
    ports:
      - '3000:3000'
  redis:
    image: 'redis'
    container_name: redis_${ENV}
    ports:
      - '6379:6379'
  postgre:
    image: 'postgres'
    container_name: postgre_${ENV}
    ports:
      - '5432:5432'
    # volumes:
      # - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DB: 'sou_qa_${ENV}'
      PGDATA: ./data

    
